#ifndef INCLUDE_ACQUISITIONPARAMETERS_H_
    #define INCLUDE_ACQUISITIONPARAMETERS_H_

    #define FORMAT_LEAP_IMAGE_WIDTH 640
    #define FORMAT_LEAP_IMAGE_HEIGHT 240
    #define FORMAT_LEAP_IMAGE_WIDTH_UNDISTORTED 640
    #define FORMAT_LEAP_IMAGE_HEIGHT_UNDISTORTED 480
#endif // SHARED_ACQUISITIONPARAMETERS_H_
